# -*- coding: utf-8 -*-
"""tredence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntnkkqLNCpzcvNoWUAmx3GTm1ch9D54d
"""

import os
import copy
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision
import torchvision.transforms as transforms


# =========================================================
# 1. Reproducibility
# =========================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


# =========================================================
# 2. CIFAR-10 Data
# =========================================================
mean = (0.4914, 0.4822, 0.4465)
std = (0.2470, 0.2435, 0.2616)

train_transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean, std),
])

test_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean, std),
])

train_dataset = torchvision.datasets.CIFAR10(
    root="./data",
    train=True,
    download=True,
    transform=train_transform
)

test_dataset = torchvision.datasets.CIFAR10(
    root="./data",
    train=False,
    download=True,
    transform=test_transform
)

train_loader = DataLoader(
    train_dataset,
    batch_size=256,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=256,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)


# =========================================================
# 3. Prunable Linear Layer
# =========================================================
class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features, gate_init=-2.0):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features

        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        self.bias = nn.Parameter(torch.zeros(out_features))

        # gate_scores has the exact same shape as weight
        self.gate_scores = nn.Parameter(torch.full((out_features, in_features), gate_init))

        nn.init.kaiming_uniform_(self.weight, a=np.sqrt(5))

        fan_in, _ = nn.init._calculate_fan_in_and_fan_out(self.weight)
        bound = 1 / np.sqrt(fan_in)
        nn.init.uniform_(self.bias, -bound, bound)

    def forward(self, x):
        gates = torch.sigmoid(self.gate_scores)
        pruned_weight = self.weight * gates
        return F.linear(x, pruned_weight, self.bias)

    def gate_values(self):
        return torch.sigmoid(self.gate_scores)


# =========================================================
# 4. Prunable MLP Model
# =========================================================
class PrunableMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()

        self.fc1 = PrunableLinear(32 * 32 * 3, 1024, gate_init=-2.0)
        self.bn1 = nn.BatchNorm1d(1024)

        self.fc2 = PrunableLinear(1024, 512, gate_init=-2.0)
        self.bn2 = nn.BatchNorm1d(512)

        self.fc3 = PrunableLinear(512, 10, gate_init=-2.0)

        self.dropout = nn.Dropout(0.2)

    def forward(self, x):
        x = self.flatten(x)

        x = self.fc1(x)
        x = self.bn1(x)
        x = F.relu(x)
        x = self.dropout(x)

        x = self.fc2(x)
        x = self.bn2(x)
        x = F.relu(x)
        x = self.dropout(x)

        x = self.fc3(x)
        return x


# =========================================================
# 5. Sparsity Utilities
# =========================================================
def compute_sparsity_loss(model):
    total = 0.0
    for module in model.modules():
        if isinstance(module, PrunableLinear):
            total = total + module.gate_values().sum()
    return total

def collect_all_gates(model):
    gates = []
    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates.append(module.gate_values().detach().cpu().view(-1))
    return torch.cat(gates)

def compute_sparsity_percent(model, threshold=1e-2):
    gates = collect_all_gates(model)
    sparse_count = (gates < threshold).sum().item()
    total_count = gates.numel()
    return 100.0 * sparse_count / total_count

def gate_stats(model):
    gates = collect_all_gates(model).numpy()
    return {
        "min": float(np.min(gates)),
        "max": float(np.max(gates)),
        "mean": float(np.mean(gates)),
        "median": float(np.median(gates)),
        "below_1e2_pct": float((gates < 1e-2).mean() * 100),
        "below_5e2_pct": float((gates < 5e-2).mean() * 100),
        "below_1e1_pct": float((gates < 1e-1).mean() * 100),
    }


# =========================================================
# 6. Evaluation
# =========================================================
@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    correct = 0
    total = 0

    for images, labels in loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        outputs = model(images)
        preds = outputs.argmax(dim=1)

        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return 100.0 * correct / total


# =========================================================
# 7. Training Function
# =========================================================
def train_one_model(lambda_target, epochs=35, warmup_epochs=10):
    model = PrunableMLP().to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_acc = 0.0
    best_acc_state = None

    best_tradeoff_score = -1e9
    best_tradeoff_state = None

    history = []

    for epoch in range(epochs):
        model.train()

        running_total_loss = 0.0
        running_cls_loss = 0.0
        running_sparse_loss = 0.0

        lambda_eff = lambda_target * min(1.0, (epoch + 1) / warmup_epochs)

        for images, labels in train_loader:
            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            optimizer.zero_grad()

            outputs = model(images)
            cls_loss = F.cross_entropy(outputs, labels)
            sparse_loss = compute_sparsity_loss(model)
            total_loss = cls_loss + lambda_eff * sparse_loss

            total_loss.backward()
            optimizer.step()

            running_total_loss += total_loss.item()
            running_cls_loss += cls_loss.item()
            running_sparse_loss += sparse_loss.item()

        scheduler.step()

        test_acc = evaluate(model, test_loader)
        sparsity = compute_sparsity_percent(model, threshold=1e-2)

        if test_acc > best_acc:
            best_acc = test_acc
            best_acc_state = copy.deepcopy(model.state_dict())

        tradeoff_score = test_acc + 0.20 * sparsity
        if tradeoff_score > best_tradeoff_score:
            best_tradeoff_score = tradeoff_score
            best_tradeoff_state = copy.deepcopy(model.state_dict())

        history.append({
            "epoch": epoch + 1,
            "lambda_target": lambda_target,
            "lambda_effective": lambda_eff,
            "train_total_loss": running_total_loss / len(train_loader),
            "train_cls_loss": running_cls_loss / len(train_loader),
            "train_sparse_loss": running_sparse_loss / len(train_loader),
            "test_accuracy": test_acc,
            "sparsity_percent_1e2": sparsity
        })

        print(
            f"Lambda={lambda_target:.1e} | "
            f"Epoch {epoch+1:02d}/{epochs} | "
            f"Acc={test_acc:.2f}% | "
            f"Sparsity={sparsity:.2f}% | "
            f"Lambda_eff={lambda_eff:.2e}"
        )

    model.load_state_dict(best_tradeoff_state)

    final_acc = evaluate(model, test_loader)
    final_sparsity = compute_sparsity_percent(model, threshold=1e-2)
    final_stats = gate_stats(model)

    return model, pd.DataFrame(history), final_acc, final_sparsity, final_stats


# =========================================================
# 8. Lambda Sweep
# =========================================================
lambda_values = [0.0, 1e-5, 5e-5, 1e-4]

all_results = []
all_histories = {}
all_models = {}

for lam in lambda_values:
    print("\n" + "=" * 80)
    print(f"Training model for lambda = {lam}")
    print("=" * 80)

    model, history_df, test_acc, sparsity, stats = train_one_model(
        lambda_target=lam,
        epochs=35,
        warmup_epochs=10
    )

    all_histories[lam] = history_df
    all_models[lam] = model

    all_results.append({
        "Lambda": lam,
        "Test Accuracy": round(test_acc, 2),
        "Sparsity Level (%)": round(sparsity, 2),
        "Gate Mean": round(stats["mean"], 4),
        "Gate Median": round(stats["median"], 4),
        "Below 0.05 (%)": round(stats["below_5e2_pct"], 2),
        "Below 0.10 (%)": round(stats["below_1e1_pct"], 2),
    })

results_df = pd.DataFrame(all_results).sort_values("Lambda")

print("\nFinal Results:")
print(results_df)


# =========================================================
# 9. Pick Best Model for Histogram
# =========================================================
candidate_rows = results_df[
    (results_df["Sparsity Level (%)"] >= 5.0) &
    (results_df["Sparsity Level (%)"] <= 70.0)
]

if len(candidate_rows) > 0:
    best_lambda = candidate_rows.sort_values("Test Accuracy", ascending=False).iloc[0]["Lambda"]
else:
    best_lambda = results_df.sort_values("Test Accuracy", ascending=False).iloc[0]["Lambda"]

best_model = all_models[best_lambda]
print(f"\nBest model chosen for histogram: lambda = {best_lambda}")


# =========================================================
# 10. Save Results
# =========================================================
os.makedirs("outputs", exist_ok=True)

results_df.to_csv("outputs/results_summary.csv", index=False)
torch.save(best_model.state_dict(), "outputs/best_prunable_mlp.pth")

for lam, hist_df in all_histories.items():
    safe_name = str(lam).replace(".", "_")
    hist_df.to_csv(f"outputs/history_lambda_{safe_name}.csv", index=False)

gates = collect_all_gates(best_model).numpy()

plt.figure(figsize=(8, 5))
plt.hist(gates, bins=100, color="steelblue", edgecolor="black")
plt.title(f"Final Gate Distribution (Best Model, lambda={best_lambda})")
plt.xlabel("Gate value")
plt.ylabel("Count")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("outputs/gate_distribution_best_model.png", dpi=200)
plt.show()

print("\nSaved files:")
print("- outputs/results_summary.csv")
print("- outputs/best_prunable_mlp.pth")
print("- outputs/gate_distribution_best_model.png")
print("- outputs/history_lambda_*.csv")